# -*- coding: utf-8 -*-
"""DesafioFinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OcbQuI2_-zVcNsjrDMzePTRaKgPNm-SW
"""

funcionarios = [{
     "nome" : "João",
     "salarioBruto" : 5000
    },
    {
     "nome" : "Carla",
     "salarioBruto" : 7000
    }]

def mostrarMenu():
  print('')
  opcao = input('O que deseja fazer? \n1 - Cadastrar Funcionário | 2 - Imprimir Contracheque | 3 - Sair' + '\n')
  if (opcao.isdigit()): 
    if (opcao == '1'):
      perguntaFuncionario()
      # print(funcionarios)
      mostrarMenu()
    elif (opcao == '2'):
      perguntaContracheque()
      mostrarMenu()
    elif (opcao == '3'):
      print('Obrigado por utilizar o sistema do RH!')
    else:
      print('> Opção inválida')
      mostrarMenu()

  else:
    print('> Opção inválida')
    mostrarMenu()

def listarFuncionarios():
  for i,funcionario in enumerate(funcionarios):
    print(str(i+1) + ' - ' + funcionario.get("nome"))

def perguntaFuncionario():
  nomeFuncionario = input('Qual o nome do funcionário?\n')

  if ((nomeFuncionario == '') or (len(nomeFuncionario) < 3) or (nomeFuncionario.isdigit())):
    print("> Digite um nome válido.\n")
    perguntaFuncionario()
  else:
    perguntaSalario(nomeFuncionario)

def perguntaSalario(nomeFuncionario):
  salario = input('Qual o salario bruto de ' + nomeFuncionario + "?\n")

  if (salario.replace('.', '', 1).isdigit()):
    funcionario = {
     "nome" : nomeFuncionario,
     "salarioBruto" : float(salario)
    }
    funcionarios.append(funcionario)
  else:
    print("> Digite um salário válido.\n")
    perguntaSalario(nomeFuncionario)

def perguntaContracheque():
  print('De quem você quer imprimir o Contracheque?')
  listarFuncionarios()
  indexFuncionario = input()
  
  if (indexFuncionario.isdigit()):
    index = int(indexFuncionario) - 1
    if ((index < len(funcionarios)) and (index >= 0)):
      funcionario = funcionarios[index]
      inss = calcularINSS(funcionario)
      irrf = calcularIRRF(funcionario, inss)
      salarioLiquido = funcionario.get("salarioBruto") - inss - irrf
      print('\n----- HOLERITE -----')
      print('Funcionário(a):  {}'.format(funcionario.get("nome")))
      print('Salário Bruto:   {}'.format(funcionario.get("salarioBruto")))
      print('Desconto INSS:   {}'.format(inss))
      print('Desconto IRRF:   {}'.format(irrf))
      print('Salário Líquido: {}'.format(round(salarioLiquido, 2)))
      print('--------------------')      
    else:
      print('> Não existe funcionário nessa posição.\n')
      perguntaContracheque()
  else:
    print('> Não existe funcionário nessa posição.\n')
    perguntaContracheque()

def calcularINSS(funcionario):
  salario = funcionario.get("salarioBruto")
  descontoINSS = 0

  if (salario <= 1045.00):
    descontoINSS = salario * 0.075
  elif (salario - 1045 >= 0):
    descontoINSS = 1045 * 0.075
  if ((salario > 1045.00) and (salario <= 2089.60)):
    descontoINSS += (salario - 1045.01) * 0.09
  elif (salario - 2089.60 > 0 ):
    descontoINSS += (2089.60 - 1045.01) * 0.09
  if ((salario > 2089.61) and (salario <= 3134.40)):
    descontoINSS += (salario - 2089.61) * 0.12
  elif (salario - 3134.40 > 0):
    descontoINSS += (3134.40 - 2089.61) * 0.12
  if ((salario > 3134.41) and (salario <= 6101.06)):
    descontoINSS += (salario - 3134.41) * 0.14
  elif (salario - 6101.06 > 0):
    descontoINSS = 713.10

  return round(descontoINSS,2)

def calcularIRRF(funcionario, inss):
  salario = funcionario.get("salarioBruto") - inss
  irrf = 0

  if ((salario > 1903.98) and (salario <= 2826.65)):
      irrf = salario * 0.075 - 142.80  
  elif ((salario > 2826.65) and (salario <= 3751.05)):
      irrf = salario * 0.15 - 354.80
  elif ((salario > 3751.05) and (salario <= 4664.68)):
      irrf = salario * 0.225 - 636.13
  elif (salario > 4664.68):
      irrf = salario * 0.275 - 869.36

  return round(irrf,2)

# ------------    

print('Bem-vindo ao sistema do RH!')
mostrarMenu()